### ISSUE TITLE
Implement Security Rules generator

### ISSUE THREAD

**Issue by kafkas** [kafkas/typesync#129]
We'll be injecting validator functions into the specified `firestore.rules` file.

**Comment by kafkas** [comment]
@mands Just finished implementing this! The Rules generator already turned out to be super useful for our early users since there isn't a good alternative! Hope you find it useful too!

If you'd like to try it out, you'll need to upgrade to v0.6. Note that this release contains some breaking changes (see [Releases](https://github.com/kafkas/typesync/releases) page). In short, `generate` has been split into multiple commands, `platform` name structure has changed and `platform` option has been renamed to `target`. For example, for Python the command will look like:

```bash
typesync generate-py --definition definition.yml --target firebase-admin@6 --outFile models.py
```

For Security Rules you'll need to specify an existing Rules file which contains "start" and "end" markers which indicate where the autogenerated validators should be inserted (see [docs](https://docs.typesync.org/cli/generate-rules)).

```bash
typesync generate-rules --definition definition.yml --outFile firestore.rules
```

Let me know if you need any help!

**Comment by mands** [comment]
Got it, that's super useful as about to implement proper security rules in our product. Will give it a try and let you know how we get on!
